### ISSUE TITLE
Add re-root capability

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#114]
KSP 1.1.0 has `EditorReRootUtil` module which seems does the trick.

**Comment by cherrydev** [comment]
Good luck!  God speed!

**Comment by ihsoft** [comment]
Alas, this module only works in editor mode, and fails with NRE when used in flight. Though, its logic can be replicated for the KIS needs.

**Comment by bwucke** [comment]
This feature gets my heartfelt upvote. KAS construction issues aside, multiple craft in the same launch make a total mess of "control from", root becoming the part that was nearest to the decoupler.

**Comment by ihsoft** [comment]
Apparently, there is no an easy way to re-root an existing vessel. In the current state of the game, a lot of the core functionality has to be re-implemented in KIS to allow the fully working re-root ability. It's not feasible at the moment.

**Comment by etmoonshade** [comment]
@ihsoft - I was going to open a new issue, but I see you've at least looked into it here. Have you looked into the potential for re-rooting again now that we're at 1.12.5 and (presumably) KSP is in a stable state?

For context, I ran into an issue where the root part was literally the ONE part I wanted to remove (a docking port, in this case) and moving the child object wasn't practical since it was, y'know, attached to an asteroid lol

Less "summoning" the Kraken and more "jumping up and down, slapping your helmet, and telling the Kraken that its mother was a hamster"

Note that moving the asteroid wouldn't even be possible if not for my patch that changes the config to allow a LOT more weight per kerbal so I don't have to have an excessive number of kerbals on EVA to move a 100t object (for example)

**Comment by ihsoft** [comment]
Re-rooting was always a big pain due to not all parts nicely support it (e.g. the physicsless surface atatched ones). The most reliable way of dealing with the situation like yours is to use the "separate tool": equip screwdriver tool and press "X". Just point on any child part to separate it with its parent.

**Comment by etmoonshade** [comment]
I ended up having to revert, trick it into using a different part as the root (a docking port,) and then had to destroy that part to get it to use a different root part. I couldn't just separate it as I recall, because it was an asteroid hatch attached to an asteroid.

Either way, not a huge deal, and probably a weird edge case - just wanted to give a poke on this issue in case the problem was "too much work for something that might break with an update" vs. "technically infeasible"
