### ISSUE TITLE
Detach of static attached part results in NPE

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#118]
160421T213532.754 [EXCEPTION] NullReferenceException: Object reference not set to an instance of an object
KIS.KISAddonPickup.OnMouseDetachPartClick (.Part part)
KIS.KISAddonCursor.Update ()

No side effect after that.

**Comment by Brusura** [comment]
I have similiar problem caused by interaction with FAR and KIS
Replicate:
launch the craft in the file, go on eva, equip the screwdriver, detach and attach the solar panel from the structural tube to the pod and you get NRE for KIS and a lot for FAR , ferram4 said is something related on how KIS create vessel

here my logs along with craft and savegame:
http://s000.tinyupload.com/index.php?file_id=41700172752221825717

FAR thread:
http://forum.kerbalspaceprogram.com/index.php?/topic/19321-11-ferram-aerospace-research-v01561-von-k%C3%A1rm%C3%A1n-42316-now-with-win64-compatibility/&do=findComment&comment=2542075

**Comment by ihsoft** [comment]
The reported behavior of FAR doesn't seem to be related to this issue root cause.
