### ISSUE TITLE
Any way to make it compatible with TweakScale?

### ISSUE THREAD

**Issue by enceos** [ihsoft/KIS#13]
Two parts of different size have same volume when stored.
![TweakScale](http://i.imgur.com/3s6XkYN.png)

**Comment by KospY** [comment]
I guess tweaking scale is done by right clicking on the part from the editor ? 
If so what I can do for that is enabling the part dragging of any part in the editor scene (instead of only the parts in the left panel). This way you can attach a part on a ship, tweak scale it and drag it in the container. Hopefully, current state of the part will be saved.

**Comment by enceos** [comment]
Would be great! I've been using a workaround, snapped scaled parts on ship and dragged them into container during flight. The current state of parts is saved, they are scaled when I take them out. But KIS currently doesn't calculate the scaled volume and mass, all scaled items have unscaled values when stored.

**Comment by KospY** [comment]
Added part dragging of any part in the editor scene  for next version (1.0.1).
About unscaled values when stored, I need more information about how tweakscale resize parts. As mods compatibilties is not priority right now, please open another issue if needed.
