### ISSUE TITLE
Kerbals entering hatch get duplicated

### ISSUE THREAD

**Issue by FalcoGer** [ihsoft/KIS#132]
Entering any hatch for any module with KIS version 1.2.7b6 (ckan version) will leave one ghost kerbal outside the hatch, stuck to the ladder. If you switch to him or her, the game will bug out, and you can't control them. The interface gets all wonky, too.
Entering works fine without KIS installed.

Log spams error:
FileNotFoundException: Could not load file or assembly, 'KIS, version 1.2.7.6, culture=neutral, PublicKeyToken=null' or one of it's dependencies.
Mods in use:
FilterExtentions, Toolbar, ABookCase Orbital Reference System, BetterCrewAssignment, Chatterer, Coherent Contracts, Contract Configurator, Contract Packs: Field Research, SCANSat and Tourism Plus, Crowd Sourced Science, Docking Port Alignment Indicator, ForScience!, Jettison, Kerbal Alarm Clock, Kerbal Attachment System (v. 0.5.7 (ckan version)), Kerbal Krash System, kOS, MechJeb 2, Module Manager (2.6.24, ckan), PlanetShine, RPM + core, RCS and Wheel sounds, SCANSat, Science- Full reward!, TweakScale, Waypoint Manager, Wider Contracts App, Interstellar Extended

**Comment by ihsoft** [comment]
Latest version on CKAN is 1.2.8. I'd suggest you've updated to it and now you have troubles.

Log record indicates KIS version incompatibility with some mod. When it happens the kerbal replication bug appears. Most likely it's KKS mod that conflicts. For some reason they require the exact KIS versions, and fail if installed mod version is different (even though it's higher).

**Comment by FalcoGer** [comment]
Very odd, I will test that.
Also confused why KKS needs KIS. They do two different things entirely.

Update: Yep, it's KKS. Although how did you find out?

**Comment by ihsoft** [comment]
Problem with KKS was first discovered in KIS/KAS alpha testing for version 1.1. Now it's just an action point: if it doesn't work check for KKS :)

Btw, all known incompatibilities are described here: https://github.com/KospY/KIS/wiki/Known-incompatible-mods. KKS issue is not here because I thought it's solved but looks like they just recompiled for the curent version (which is not a fix, actually).

**Comment by StrandedonEarth** [comment]
I updated KAS/KIS via CKAN today and now I'm getting this bug too. Mod list is attached. 
What happens if I try to uninstall KIS/KAS, given that I now have some parts in inventories in flight?
I'm running 1.1.2

![mods](https://cloud.githubusercontent.com/assets/19159647/14972617/c13a71b2-1092-11e6-8b17-a9fed3e63307.png)

**Comment by ihsoft** [comment]
If you uninstall KIS&KAS then vessels that use the parts won't load. I'd suggest uninstalling KKS instead. Another option is downgrading to 1.2.7 and waiting till KKS is fixed.

**Comment by StrandedonEarth** [comment]
Ok, now I feel like an idiot. I didn't realize what KKS stood for before I posted and didn't think I had it. But yes, that solved the problem, thanks.

**Comment by ihsoft** [comment]
Nothing can be done here for now. Every time a new version of KIS is released any mod that depends on it will start failing. The consequences of such failure can be very different. Kerbal replication is just one of the most known (and annoying) one.

KSP 1.1 requires version of the dependent libraries to match exactly, and it doesn't check if the existing version is more fresh. So, for now the only way to fix the issue is requesting the author of the depending mod to do a rebuild.
