### ISSUE TITLE
Compatibility issue with Near Future Solar

### ISSUE THREAD

**Issue by JeffreyCor** [ihsoft/KIS#15]
When KIS and Near Future Solar are both installed the category does not show up. This may also be the cause of ships saved with items in KIS slots do not load correctly. With Near Future Solar removed KIS seems to have everything come up normally (note insufficient testing to confirm vessel load error also removed without Near Future Solar installed)
UPDATE: Vessel saving issue is separate and not connected to the problem with Near Future Solar

**Comment by PadroneSF** [comment]
By chance, are you using Quicksearch and/or FilterExtensions?  I thought I had a similar issue after installing KIS.  But after a lot of testing, for me the issue was both Quicksearch and FilterExtensions are not playing well with KIS. 

My experience: The "Filter by Manufacturer" search icon only shows the container and its mounting base, not the other five items, even tho their Mfg. is listed as "KIS".

Using "Filter by Function" (the top left icon) and looking 10 items down the icon column that shows up, I see "EVA Items" with a kerbanaut for the icon.  That shows the wrench, screwdriver, propellant, explosive and manual, but not the container and base, which makes sense.

I'm not sure this will help, but I thought I'd share my thoughts.

**Comment by JeffreyCor** [comment]
I do you QuickSearch but not FilterExtensions, however removing that did not correct the problem with the category not showing. I started removing and retrying all mods I had, focusing on those in common with another user that indicated the same problem. After much trial and error it was only when Near Future Solar was installed that the issue occurred. QuickSearch with NFS removed permits expected function from KIS so ruled out QS as a cause due to this.

**Comment by KospY** [comment]
Seem not related to KIS
