### ISSUE TITLE
Engineers should gain XP when moving parts around

### ISSUE THREAD

**Issue by drewcassidy** [ihsoft/KIS#162]
Engineers should gain experience as they move parts around. I have a kerbal in orbit that has assembled an entire station and is still only single star. This would also work well with #54

**Comment by ihsoft** [comment]
The main question here is _how_ they should gain the experience. Do you have any ideas? Just giving some credit for moving/attaching part in any situation doesn't seem to be a good idea as it spoils the game's level approach.

**Comment by drewcassidy** [comment]
It could be proportional to the objects mass. Moving lights and antennas gives very little XP, moving large station modules gives much much more

**Comment by ihsoft** [comment]
In general, getting XP should be a challenge. If there is no challenge then XP system makes no sense. E.g. in sandbox mode everybody has 5 star level.

I see a challenge in getting to Mun/Minmus/Sun orbit, but what is the challenge of moving a 100kg object? How is it different from moving a 1t object?

**Comment by drewcassidy** [comment]
perhaps it can have diminishing returns depending on where its done? moving things in kerbin orbit can only get you to 1 star, moving things on the mun gets you to 2, etc.

**Comment by drewcassidy** [comment]
In other words, attaching things would be another XP giver alongside planting flags http://wiki.kerbalspaceprogram.com/wiki/Experience

**Comment by ihsoft** [comment]
In the stock game approach there is a key point: you cannot add XP by repeating the same action. E.g. if you plant flag on Mun ten times in a row by the same kerbal you won't get 50XP, you get 5XP for the first try and 0 for the others. With KIS (as you propose it) it's different since you can attached/detach things indefinitely.

For the game to stay fun the XP upgrade must:
1. Require a challenging action from the user. Simple attaching of a part is not a challenge, it's a routine operation.
2. Not to be boring. Example of a "boring approach" is giving a very little XP for every trivial KIS action (like 0.01XP). You will get a level eventually but to reach it you have to spend hours in EVA.

Some examples which I do see as challenges:
1. Pickup a part that is heavier than 1t. Challenge: you need more than one kerbal in EVA.
2. Build a vessel consisting of minimal set of parts (e.g. command module, wheels, solar panels, etc.) on a surface of a celestial body. Challenge: you need to bring the parts on the surface and have them assembled into a rover.
3. And so on. Main idea is a clear objective that requires concrete efforts.

**Comment by drewcassidy** [comment]
That makes sense.

also, one of the stock methods of gaining XP is to plant a flag. Once you land on a body, planting a flag isnt exactly a challenge...

**Comment by ihsoft** [comment]
In whole, this feature doesn't seem to be feasible. The XP points must be hard to earn. It's by the design. And KIS is designed to make all the actions as easy as possible.
