### ISSUE TITLE
Part is created on the kerbal instead of the target vessel

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#197]
Details here: http://forum.kerbalspaceprogram.com/index.php?/topic/142594-12-kerbal-attachment-system-kas-v062/&do=findComment&comment=2935982

Brief analysis:
* No obvious errors.
* Part is created as physcsless.

**Comment by pellinor0** [comment]
I have seen this too, but could only reproduce it in a heavily modded install. In my case it only happened for physicsless parts that were taken directly out of an inventory. Grabbing and reattaching the part fixed the attachment.

**Comment by ghost** [comment]
Here's a log that has me exiting to the space center and then quitting to the menu and exiting, instead of just alt-f4'ing after the issue occurred. It's got more stuff in it, but none of it looks terribly helpful:
https://drive.google.com/open?id=0B4ps98pMWaZnSXMxYzcyQWIyWkU

>Grabbing and reattaching the part fixed the attachment.

Thanks for mentioning that! That seems to work for me too, so at least I can continue playing. I was a bit afraid I'd managed to irrevocably break things.

For ease of reference, I'll quote my post on the Forums:

>I'm getting a weird issue where a kerbal is attaching parts to *themself* rather than the ship. (The parts appear to attach to the ship, but then when the kerbal moves away the parts follow along with it.)
To reproduce from this save, I can just EVA the kerbal in the only ship in the save, and try to attach the lights or demolition charge to the ship.

>The issue still occurs after save/load, and even restarting KSP.

>KSP.log:
>https://drive.google.com/open?id=0B4ps98pMWaZnTmU2dGdnc3E5X28

>quicksave.loadmeta:
>https://drive.google.com/open?id=0B4ps98pMWaZnRVNoblBoVHdIdms

>quicksave.sfs:
>https://drive.google.com/open?id=0B4ps98pMWaZnT2E5eHpWdWd0QXc

>Mods in this save:
>ModuleManager v2.7.5
>KIS v 1.4.1
>KAS v0.6.2

>The issue originally occurred with more mods, but it still occurs after pruning the ship down to just the basics and loading/saving in a KSP install with only these three mods.


I've also attached the files here:

[KSP.log.txt](https://github.com/ihsoft/KIS/files/736319/KSP.log.txt)
[quicksave.loadmeta.txt](https://github.com/ihsoft/KIS/files/736320/quicksave.loadmeta.txt)
[quicksave.sfs.txt](https://github.com/ihsoft/KIS/files/736321/quicksave.sfs.txt)
[(second) KSP.log.txt](https://github.com/ihsoft/KIS/files/736322/second.KSP.log.txt)

**Comment by ihsoft** [comment]
Interesting. I was not able to reproduce the problem on the launchpad but it indeed shows up when using this save file.
