### ISSUE TITLE
Intermitently cannot access inventory on EVA, EVA items and containers duplicated or empty on VAB.

### ISSUE THREAD

**Issue by dronkit** [ihsoft/KIS#215]
From time to time, it happens more or one of the following:

-The categories "EVA items" and "Containers" are empty in VAB, though I can access the seats inventories in the command pods. The items belonging to those categories, however, are found in the "utilities" and "payload" categories.
-The categories "EVA items" and "containers" are duplicated in the VAB category list.
-Although the seats inventories in the command pods are available in VAB, when launching, I cannot acces the kerbal's inventories in EVA. Right-clicking on them has no "inventory" button. There's no "inventory" buttons on the command pods either. Neither do TAB keys or others such as "g" work. When approaching a container and right clicking, the button "inventory" appears but nothing happens on click.

My modulemanager is 2,8,1

This ksp.log is from a situation in which the second and third items are happening.

[KSP.log.zip](https://github.com/ihsoft/KIS/files/1132912/KSP.log.zip)

**Comment by ihsoft** [comment]
I've checked the log and didn't found any error related to KIS. Moreover, the records in the log indicate a normal KIS work.

However, I see a major problem in your mods setup. There are at least three mods that failed to load properly: `AnomalySurveyor`, `ToadicusTools`, and `TweakableDeployablePanels`. Once the game is loaded, the log becomes flooded with critical errors from various modules. E.g.:
```
[ERR 07:10:16.043] Module DMSeismicSensor threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at DMagic.Part_Modules.DMBasicScienceModule.findContainers () [0x00000] in <filename unknown>:0 
  at DMagic.Part_Modules.DMBasicScienceModule.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at DMagic.Part_Modules.DMSeismicSensor.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 
```
or an endless serie of:
```
[EXC 07:10:48.309] NullReferenceException
	Kopernicus.RuntimeUtility.LateUpdate ()
[EXC 07:10:48.312] NullReferenceException
	Kopernicus.Components.KopernicusStar.<Awake>b__10_1 (UnityEngine.Camera cam)
	UnityEngine.Camera.FireOnPreCull (UnityEngine.Camera cam)
```
etc.

That said, even if there is a problem in KIS, it's impossible to locate it until the other issues are fixed. You may try removing the failing mods and test if the issue is still there.

**Comment by dronkit** [comment]
Thanks for your thoroughness! I'll report if hte issue happens again without those other mods.

**Comment by ihsoft** [comment]
Closing it for now. feel free to reopen if the issue comes back.
