### ISSUE TITLE
Request: Remove the hardcoded "item removing on unoccupied seats"

### ISSUE THREAD

**Issue by Gordon-Dry** [ihsoft/KIS#262]
See
https://forum.kerbalspaceprogram.com/index.php?/topic/149848-14-kerbal-inventory-system-kis-v112/&do=findComment&comment=3409735

I put the same KIS items into the inventory of all seats on both the Mun orbiter and the lander, but the lander's inventory is empty for all Kerbals.

When then crew will occupy the seats then, they should have their items ...

**Comment by mwerle** [comment]
I've been bitten by this as well, but it's not so easy to resolve. Consider how the mod should handle the case where a Kerbal either enters the pod from EVA and is already carrying some KIS items, or transfers seats within the ship?

What should happen if the total number of items now exceeds the seat allowance?

In the case of swapping seats, it's "easy" - leave the items in the old seat, although players can still get confused because the Kerbal doesn't have the item(s) that they thought it should have.

In the case of entering from EVA, what should happen? Should the items the Kerbal is carrying be destroyed or dropped outside the capsule?

**Comment by ihsoft** [comment]
I've explained this case on the forum. Here is the summary: the seat inventories are _not_ containers! It's totally incorrect to consider them like this. The best analogue to the seat inventory is the kerbal spacesuit pockets. You cannot send to space a spacesuit without kerbal, and so you cannot send items in its pockets.

When you need to send stuff to orbit, you have to add a _container part_ to the vessel. Add a part that is specifically designed to be a container, or apply a patch to the pod parts to add an inventory module if you see it appropriate. The seat inventories will not solve the case. They exist for the only purpose to keep the kerbals "pocket contents".
