### ISSUE TITLE
Allow grab hints menu to be turned off in KIS settings.cfg

### ISSUE THREAD

**Issue by TonkaCrash** [ihsoft/KIS#305]
Grab hints menu can interfere with placing parts by obscuring the target area. Please allow the hints menu to be turned off. Simple would be to toggle it off completely in the settings.cfg file. Snazzier would be to have it fade out after a time delay set in the settings.cfg file with zero time meaning it's never present.  After using KIS nearly daily for months, the hints menu has become more of a nuisance than aid.

**Comment by ihsoft** [comment]
The fix is implemented with a bonus. Not only the hint text can now be disabled via settings. It's also possible to hide both the icon and the text by depressing a selected key (`G` by default). This can be used to temporarily remove any `KIS` GUI elements to verify if the part, being attached, fits well the target.
