### ISSUE TITLE
pod inventory is lost when...

### ISSUE THREAD

**Issue by kitoma** [ihsoft/KIS#50]
I launched a ship for one of these "rescue stranded kerbal" missions (probe-controlled, one empty Mk1 capsule), and added a wrench, screw-driver, battery and 2 solar panels to the pod/seat-0 inventory (to be prepared in case that kerbal happened to be an engineer). On the launch pad, the inventory is still there (verified in the quicksave). After rendezvous in orbit and successful EVA-transfer of the kerbal, all items are lost. I kind of understand why it happens (the stranded kerbal of cause did not have any items, and I guess the pod-inventory just gets replaced with that of the boarding kerbal), but it "doesn't feel right".

Can be reproduced on the launchpad:
- launch a pod with something (a wrench..) in the inventory
- check via any suiteable method that items are in the pod (savegame, debug log?)
- walk Jeb (with an empty personal inventory) over and board
- observe all items formerly stored in the pod having being lost (no trace of them in the savegame)

Obviously not quite trivial to solve, especially in cases of conflicts (volume, slots).

**Comment by enceos** [comment]
It feels right. Because these pod inventories are actually Kerbal's pockets. If there's no Kerbal inside, then there are no pockets.

It's gonna be user unfriendly if you won't be able to stuff seat inventories in the VAB until you actually fill that place with a Kerbal. So don't stuff Kerbal's pockets when there will be no Kerbal there. If you want your pod to have an inventory you know what to do.

**Comment by kitoma** [comment]
Because of the way it is phrased ("seat X inventory"), I always assumed the stuff is in the snacks locker next to the seat, or under the seat, or  something similar. So that's why for me it totally made sense to fill up that locker, instead of MM'ing the pod to add a separate inventory (which I'ld rather avoid for all the obvious and some maybe not so obvious reasons).

Anyway, KospY, if you intended it that way (deep pockets), then please close the ticket as will-not-fix.

**Comment by KospY** [comment]
As Enceos explained, pod inventories are actually Kerbal's inventories.
I can't use them as a "locker" because I can't prevent a kerbal entering a pod with a full inventory (to avoid overwriting locker content).

I cannot change the way it work, however I can change "seat X inventory" text to something else or add a warning message somewhere ?

**Comment by Phalen** [comment]
I got frustrated by that to, the way I read it was locker space per kerbal vs kerbal pocket.  I built a mining rover tested it out and hated how the original crew pod worked... decided to put some toys in the remake to test with and got peved when they disapeard.   

launch pad inventory for seated kerbal #1 inventory  might be the best description possible.
