### ISSUE TITLE
Full Inventory vanishes when entering into a Hitchhiker Storage Container

### ISSUE THREAD

**Issue by BalrogGamer** [ihsoft/KIS#98]
I had an engineer doing some cleanup work on the outside of my space station - removing excess batteries and such. When I had him enter into a PPD-10 Hitchhiker Storage Container, all the items in his inventory vanished - including his screwdriver, and hard drives full of data.

As a workaround, I'm going to be sure to transfer all items OFF an EVA Kerbal before re-entering the station.

**Comment by ihsoft** [comment]
Can you reliable reproduce the issue or it's an intermittent behavior?

**Comment by WazWaz** [comment]
Same happens when entering MK-V Inflatable Habitation Module and a number of other modules.

https://github.com/BobPalmer/MKS/issues/873

It happens every time with this, but not always with the Hitchhiker Storage Container (never in my testing).

The MK-V Inflatable Habitation Module never gets a ModuleKISInventory module added to it.

**Comment by ihsoft** [comment]
I can add a check if target module has inventory but what to do if it doesn't? Block entering the module? It doesn't seem to be a good idea. Move inventory into some othe storage on the station? Sounds like an option but if there is no other containers or they don't have enough space we get the same problem.

**Comment by WazWaz** [comment]
The problem is that ModuleKISInventory is only added for each crewcapacity slot using the initial CrewCapacity property, not when this property changes (i.e. when the Hab inflates). MKS prevents deflating the module when someone is on board, so it should not be a problem (gameplay wise) to remove the ModuleKISInventory when CrewCapacity goes down and add it when CrewCapacity goes up, since it is MKS's job to ensure it doesn't go down while there is a crew member with inventory on board. I'm thinking this bug is not actually the same as was originally reported with the Hitchhiker crewcabin.

**Comment by ihsoft** [comment]
Yeah, inventories in modules with variable number of seats is a pain for now. Module code must take care of it for now. I'm thinking on a solution to support it at KIS side transparently.

**Comment by WazWaz** [comment]
Would it be possible to drop the items outside the hatch and give a message, so at least the parts are retrievable? The big problem is that losing your screwdriver on a distant planet is rather dire. Or even better, refuse entry the same way carrying science into such parts gives a warning that they'll be lost.

**Comment by ihsoft** [comment]
Need to investigate how they did it with science. If there is a way to itercept enter action before it actually happens then it may work.

**Comment by JadeFalcon-1** [comment]
I thought it _did_ drop the items outside of the module. I hit this issue when entering a habitation module that was on a base that was moving _very_ slowly downhill (dont ask), and the tools that were in my kerbals hand were hanging in midair just outside the hatch, you just couldn't interact with them.  Returning to the Space Center made them go away completely.  So it could be that they "drop" inside the model of the Habitation module, and you just don't see them because ideally, the module wouldn't be moving.

**Comment by ihsoft** [comment]
Whatever you saw was a unexpected behavior. Dropping parts is not as simple action as it sounds. If parts are dropped at the position of kerbal then next thing that will happen is their colliders hitting the kerbal. Dropping parts at some distance from kerbal is just a part of the solution since you never know which direction of this "distance" is safe. Not to mention that many things explode being dropped on the ground.

I'd say that "dropping parts" is the worst solution of this issue. After all, player can drop the parts manually if this is really a last resort. And good news here is that manual dropping will not hit colliders.
